/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RssGeneratorRouteImport } from './routes/rss-generator'
import { Route as EcommerceFeedsRouteImport } from './routes/ecommerce-feeds'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RssGeneratorRoute = RssGeneratorRouteImport.update({
  id: '/rss-generator',
  path: '/rss-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceFeedsRoute = EcommerceFeedsRouteImport.update({
  id: '/ecommerce-feeds',
  path: '/ecommerce-feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/ecommerce-feeds': typeof EcommerceFeedsRoute
  '/rss-generator': typeof RssGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/ecommerce-feeds': typeof EcommerceFeedsRoute
  '/rss-generator': typeof RssGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/ecommerce-feeds': typeof EcommerceFeedsRoute
  '/rss-generator': typeof RssGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/docs' | '/ecommerce-feeds' | '/rss-generator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/docs' | '/ecommerce-feeds' | '/rss-generator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/docs'
    | '/ecommerce-feeds'
    | '/rss-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocsRoute: typeof DocsRoute
  EcommerceFeedsRoute: typeof EcommerceFeedsRoute
  RssGeneratorRoute: typeof RssGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rss-generator': {
      id: '/rss-generator'
      path: '/rss-generator'
      fullPath: '/rss-generator'
      preLoaderRoute: typeof RssGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-feeds': {
      id: '/ecommerce-feeds'
      path: '/ecommerce-feeds'
      fullPath: '/ecommerce-feeds'
      preLoaderRoute: typeof EcommerceFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
  EcommerceFeedsRoute: EcommerceFeedsRoute,
  RssGeneratorRoute: RssGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
